name: DateCalculator
main: com.github.pietw3lve.datecalculator.DateCalculatorPlugin
version: 1.0.0
api-version: 1.15
author: PieTw3lve
website: https://github.com/PieTw3lve/DateCalculator
description: A straightforward and lightweight plugin that enables you to calculate dates.

# This sets PlaceholderAPI as a dependency for your plugin.
depend: [PlaceholderAPI]
